[project]
name = "asteroids"
version = "0.1.0"
description = "An asteroids collision pygame developed from tutorial from boot.dev"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pygame==2.6.1",
]
